graph TD
    A[FastAPI_Gateway] --> B[run(input_data).py]
    B --> C[task_classifier.py]
    C --> D[EngineHub.py]
    D --> E1[SlizzAI-2 (NLP)]
    D --> E2[SlizzAI-3 (Vision)]
    D --> E3[SlizzAI-4 (Logic)]
    D --> E4[SlizzAI-5 (Speech)]
    D --> E5[SlizzAI-6 (Retrieval)]
    B --> F[memory_cache.py]
    B --> G[logging.py]
    B --> H[feedback_loop.py]
    A --> I[rate-limiter.py]
    A --> J[health_check.py]